#!/bin/sh

set -eu

LIB="${TEST_DIR}/bats/lib"
#shellcheck source=bats/lib/assert-crowdsec-not-running.sh
. "${LIB}/assert-crowdsec-not-running.sh"

CSCLI="${BIN_DIR}/cscli"
CROWDSEC="${BIN_DIR}/crowdsec"

"${TEST_DIR}/instance-data" load

hubdir="${LOCAL_DIR}/hub-tests"
mkdir -p "${hub-tests}"
git clone --depth 1 https://github.com/crowdsecurity/hub.git "${hubdir}"

HUBTESTS_BATS="${TEST_DIR}/bats/99_hubtests.bats"

cat <<EOT > "${HUBTESTS_BATS}"
set -u

LIB="\${TEST_DIR}/bats/lib"
load "\${LIB}/bats-support/load.bash"
load "\${LIB}/bats-assert/load.bash"

CSCLI="\${BIN_DIR}/cscli"
CROWDSEC="\${BIN_DIR}/crowdsec"

EOT

for testname in $("${CSCLI}" --crowdsec "${CROWDSEC}" --cscli "${CSCLI}" hubtest --hub "${hubdir}" list -o json | grep -v NAME | grep -v -- '-------' | awk '{print $1}'); do
    cat << EOT >> "${HUBTESTS_BATS}"

@test "$testname" {
    run "\${CSCLI}" --crowdsec "\${CROWDSEC}" --cscli "\${CSCLI}" --hub "${hubdir}" hubtest run "${testname}" --clean
    # in case of error, need to see what went wrong
    echo "\$output"
    assert_success
}
EOT
done
